print("\033[1;32;40m")
#print("╔"+"═"*20+"╗")
print("╔═══════════════════════════╗")
print("║    PYTHON ÇALIŞMALARI     ║")
print("║                           ║")
print("║ 1-HESAP MAKİNESİ          ║") #╝,╚,c,║
print("║ 2-OYUNLAR                 ║")
print("║ 3-ŞEKİL ÇİZDİRME          ║")
print("║ 4-TAKVİM                  ║")
print("║ 5-RİTMİK SAYMA            ║")
print("║ 6-NOT HESAPLAMA           ║")
print("║ 7-ÇARPIM TABLOSU          ║")
print("║ 8-BMI HESAPLAMA           ║")
print("║ 9-DÖVİZ UYGULAMASI        ║")
print("║ 10-SICAKLIK ÇEVİRME       ║")
print("║ 11-ÇIKIŞ (é)              ║")
print("║                           ║")
print("║       Seçimini yap        ║")
print("╚═══════════════════════════╝")
